project:
  type: website
  output-dir: docs

website:
  title: "Home"
  navbar:
    left:
      - href: about.qmd
        text: About
      - href: research/index.qmd
        text: Research
      - href: Julia_Chahine_Resume__NO_GPA___May_2023_Update.pdf
        text: CV

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor:
  render-on-save: true
